/*
 * BIT707 - Assignment 3
 * Jason Norton - 5001428
 */
package BIT707_A3_5001428_ToDoList;

import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import javax.swing.plaf.InternalFrameUI;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 * Displays tasks to the user organised by days of the week for the selected week (this week by default)
 */
public class CalendarViewForm extends javax.swing.JInternalFrame {

    /**
     * Creates new CalendarViewForm and populates it with data
     */
    public CalendarViewForm() {
        initComponents();
        // Removes title bar from jInternalForm
        InternalFrameUI internalFrameUI = this.getUI();
        ((BasicInternalFrameUI)internalFrameUI).setNorthPane(null);
        
        // Removes the header row from jTable        
        jTable_calendarView.setTableHeader(null);
        
        // Hides delete button until an item is selected
        jButton_deleteSelectedTask.setVisible(false);
        
        // Sets dates for current week 
        App.controller.setSelectedWeek(0);
        jLabel_currentWeek.setText(App.controller.getSelectedWeek());
        
        // Gets data for the jTable
        App.controller.populateTableData(jTable_calendarView);  
        
        // Handles double mouse clicks on table rows
        App.controller.addTableMouseClickListener(jTable_calendarView, jDialog_viewTask);
    }
    
    /**
     * Displays a dialog on screen containing an error message.
     * @param message 
     */
    public void displayErrorMessage(String message) {
        jTextArea_errorDialogMessage.setText("message");
        // Displays dialog position in the centre of the parent form
        jDialog_errorDialog.setLocationRelativeTo(this.jScrollPane_calendarView);
        jDialog_errorDialog.setVisible(true);
    }
        
    /**
     * Displays a dialog on screen showing a detailed view of the selected task
     * @param taskComponents 
     */
    public void displayTask(ArrayList<String> taskComponents) {
        jTextField_viewTaskName.setText(taskComponents.get(1));
        jTextArea_viewTaskDetails.setText(taskComponents.get(2));
        jTextField_viewTaskDate.setText(taskComponents.get(3));
        // Changes button text based on task status 
        boolean status = Boolean.parseBoolean(taskComponents.get(4));
        if(status) {
            jButton_viewTaskMarkCompleted.setText("Mark as incomplete");
        }
        else {
            jButton_viewTaskMarkCompleted.setText("Mark as completed");
        }
        // Displays the dialog box in the centre of the parent form
        jDialog_viewTask.setLocationRelativeTo(this.jScrollPane_calendarView);
        jDialog_viewTask.setName(taskComponents.get(0));
        jDialog_viewTask.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_addTask = new javax.swing.JDialog();
        jPanel_addTaskPanel = new javax.swing.JPanel();
        jButton_addTaskSave = new javax.swing.JButton();
        jTextField_addTaskName = new javax.swing.JTextField();
        jTextField_addTaskDate = new javax.swing.JTextField();
        jScrollPane_addTask = new javax.swing.JScrollPane();
        jTextArea_addTaskDetails = new javax.swing.JTextArea();
        jButton_addTaskCancel = new javax.swing.JButton();
        jLabel_addTaskDetailsIcon = new javax.swing.JLabel();
        jLabel_addTaskDateIcon = new javax.swing.JLabel();
        jPanel_addTaskErrorMessage = new javax.swing.JPanel();
        jLabel_addTaskErrorMessage = new javax.swing.JLabel();
        jDialog_viewTask = new javax.swing.JDialog();
        jPanel_viewTaskPanel = new javax.swing.JPanel();
        jButton_viewTaskMarkCompleted = new javax.swing.JButton();
        jTextField_viewTaskName = new javax.swing.JTextField();
        jTextField_viewTaskDate = new javax.swing.JTextField();
        jScrollPane_viewTask = new javax.swing.JScrollPane();
        jTextArea_viewTaskDetails = new javax.swing.JTextArea();
        jLabel_viewTaskDetailsIcon = new javax.swing.JLabel();
        jLabel_viewTaskDateIcon = new javax.swing.JLabel();
        jButton_editTask = new javax.swing.JButton();
        jDialog_editTask = new javax.swing.JDialog();
        jPanel_editTaskPanel = new javax.swing.JPanel();
        jButton_editTaskSave = new javax.swing.JButton();
        jTextField_editTaskName = new javax.swing.JTextField();
        jTextField_editTaskDate = new javax.swing.JTextField();
        jScrollPane_editTask = new javax.swing.JScrollPane();
        jTextArea_editTaskDetails = new javax.swing.JTextArea();
        jButton_editTaskCancel = new javax.swing.JButton();
        jLabel_editTaskDetailsIcon = new javax.swing.JLabel();
        jLabel_editTaskDateIcon = new javax.swing.JLabel();
        jPanel_editTaskErrorMessage = new javax.swing.JPanel();
        jLabel_editTaskErrorMessage = new javax.swing.JLabel();
        jDialog_errorDialog = new javax.swing.JDialog();
        jPanel_errorMessagePanel = new javax.swing.JPanel();
        jTextArea_errorDialogMessage = new javax.swing.JTextArea();
        jButton_errorDialogContinue = new javax.swing.JButton();
        jPanel_calendarView = new javax.swing.JPanel();
        jLabel_calendarViewStatus = new javax.swing.JLabel();
        jScrollPane_calendarView = new javax.swing.JScrollPane();
        jTable_calendarView = new javax.swing.JTable();
        jPanel_addTaskButtons = new javax.swing.JPanel();
        jButton_addTask = new javax.swing.JButton();
        jButton_deleteSelectedTask = new javax.swing.JButton();
        jButton_calendarView_lastWeek = new javax.swing.JButton();
        jButton_calendarView_nextWeek = new javax.swing.JButton();
        jLabel_currentWeek = new javax.swing.JLabel();
        jButton_resetSelectedWeek = new javax.swing.JButton();

        jDialog_addTask.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_addTask.setTitle("Add Task");
        jDialog_addTask.setAlwaysOnTop(true);
        jDialog_addTask.setBackground(new java.awt.Color(79, 79, 79));
        jDialog_addTask.setFocusTraversalPolicyProvider(true);
        jDialog_addTask.setIconImage(null);
        jDialog_addTask.setIconImages(null);
        jDialog_addTask.setLocation(new java.awt.Point(0, 0));
        jDialog_addTask.setMinimumSize(new java.awt.Dimension(480, 435));
        jDialog_addTask.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialog_addTask.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        jDialog_addTask.setName(""); // NOI18N
        jDialog_addTask.setResizable(false);

        jPanel_addTaskPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_addTaskPanel.setName("jPanel_addTaskPanel"); // NOI18N

        jButton_addTaskSave.setBackground(new java.awt.Color(75, 114, 153));
        jButton_addTaskSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_addTaskSave.setForeground(new java.awt.Color(255, 255, 255));
        jButton_addTaskSave.setText("Save");
        jButton_addTaskSave.setName("jButton_addTaskSave"); // NOI18N
        jButton_addTaskSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addTaskSaveActionPerformed(evt);
            }
        });

        jTextField_addTaskName.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_addTaskName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_addTaskName.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_addTaskName.setText("Enter task name");
        jTextField_addTaskName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextField_addTaskName.setName("jTextField_addTaskName"); // NOI18N
        jTextField_addTaskName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_addTaskNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_addTaskNameFocusLost(evt);
            }
        });

        jTextField_addTaskDate.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_addTaskDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_addTaskDate.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_addTaskDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_addTaskDate.setText("dd-mm-yyyy");
        jTextField_addTaskDate.setName("jTextField_addTaskDate"); // NOI18N
        jTextField_addTaskDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_addTaskDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_addTaskDateFocusLost(evt);
            }
        });

        jScrollPane_addTask.setName("jScrollPane_addTask"); // NOI18N

        jTextArea_addTaskDetails.setBackground(new java.awt.Color(224, 224, 244));
        jTextArea_addTaskDetails.setColumns(20);
        jTextArea_addTaskDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_addTaskDetails.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_addTaskDetails.setLineWrap(true);
        jTextArea_addTaskDetails.setRows(5);
        jTextArea_addTaskDetails.setText("Add task details");
        jTextArea_addTaskDetails.setWrapStyleWord(true);
        jTextArea_addTaskDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextArea_addTaskDetails.setName("jTextArea_addTaskDetails"); // NOI18N
        jTextArea_addTaskDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea_addTaskDetailsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea_addTaskDetailsFocusLost(evt);
            }
        });
        jScrollPane_addTask.setViewportView(jTextArea_addTaskDetails);

        jButton_addTaskCancel.setBackground(new java.awt.Color(75, 114, 153));
        jButton_addTaskCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_addTaskCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_addTaskCancel.setText("Cancel");
        jButton_addTaskCancel.setName("jButton_addTaskCancel"); // NOI18N
        jButton_addTaskCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addTaskCancelActionPerformed(evt);
            }
        });

        jLabel_addTaskDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comment.png"))); // NOI18N
        jLabel_addTaskDetailsIcon.setName("jLabel_addTaskDetailsIcon"); // NOI18N

        jLabel_addTaskDateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar.png"))); // NOI18N
        jLabel_addTaskDateIcon.setName("jLabel_addTaskDateIcon"); // NOI18N

        jPanel_addTaskErrorMessage.setBackground(new java.awt.Color(224, 224, 244));
        jPanel_addTaskErrorMessage.setName("jPanel_addTaskErrorMessage"); // NOI18N

        jLabel_addTaskErrorMessage.setBackground(new java.awt.Color(69, 69, 69));
        jLabel_addTaskErrorMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_addTaskErrorMessage.setForeground(new java.awt.Color(204, 0, 102));
        jLabel_addTaskErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_addTaskErrorMessage.setName("jLabel_addTaskErrorMessage"); // NOI18N

        javax.swing.GroupLayout jPanel_addTaskErrorMessageLayout = new javax.swing.GroupLayout(jPanel_addTaskErrorMessage);
        jPanel_addTaskErrorMessage.setLayout(jPanel_addTaskErrorMessageLayout);
        jPanel_addTaskErrorMessageLayout.setHorizontalGroup(
            jPanel_addTaskErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_addTaskErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_addTaskErrorMessageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_addTaskErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_addTaskErrorMessageLayout.setVerticalGroup(
            jPanel_addTaskErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
            .addGroup(jPanel_addTaskErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_addTaskErrorMessageLayout.createSequentialGroup()
                    .addComponent(jLabel_addTaskErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel_addTaskPanelLayout = new javax.swing.GroupLayout(jPanel_addTaskPanel);
        jPanel_addTaskPanel.setLayout(jPanel_addTaskPanelLayout);
        jPanel_addTaskPanelLayout.setHorizontalGroup(
            jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addTaskPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_addTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_addTaskPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_addTaskDetailsIcon)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_addTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_addTaskPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_addTaskDateIcon)
                            .addGroup(jPanel_addTaskPanelLayout.createSequentialGroup()
                                .addComponent(jButton_addTaskSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_addTaskCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel_addTaskErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_addTaskPanelLayout.setVerticalGroup(
            jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_addTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_addTaskDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_addTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_addTaskDateIcon))
                .addGap(29, 29, 29)
                .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_addTaskSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_addTaskCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_addTaskErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_addTaskLayout = new javax.swing.GroupLayout(jDialog_addTask.getContentPane());
        jDialog_addTask.getContentPane().setLayout(jDialog_addTaskLayout);
        jDialog_addTaskLayout.setHorizontalGroup(
            jDialog_addTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_addTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_addTaskLayout.setVerticalGroup(
            jDialog_addTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_addTaskLayout.createSequentialGroup()
                .addComponent(jPanel_addTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialog_viewTask.setTitle("View Task");
        jDialog_viewTask.setAlwaysOnTop(true);
        jDialog_viewTask.setBackground(new java.awt.Color(79, 79, 79));
        jDialog_viewTask.setFocusTraversalPolicyProvider(true);
        jDialog_viewTask.setIconImage(null);
        jDialog_viewTask.setIconImages(null);
        jDialog_viewTask.setLocation(new java.awt.Point(0, 0));
        jDialog_viewTask.setMinimumSize(new java.awt.Dimension(480, 435));
        jDialog_viewTask.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialog_viewTask.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        jDialog_viewTask.setName(""); // NOI18N
        jDialog_viewTask.setResizable(false);

        jPanel_viewTaskPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_viewTaskPanel.setName("jPanel_viewTaskPanel"); // NOI18N

        jButton_viewTaskMarkCompleted.setBackground(new java.awt.Color(75, 114, 153));
        jButton_viewTaskMarkCompleted.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_viewTaskMarkCompleted.setForeground(new java.awt.Color(255, 255, 255));
        jButton_viewTaskMarkCompleted.setText("Mark as completed");
        jButton_viewTaskMarkCompleted.setName("jButton_viewTaskMarkCompleted"); // NOI18N
        jButton_viewTaskMarkCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewTaskMarkCompletedActionPerformed(evt);
            }
        });

        jTextField_viewTaskName.setEditable(false);
        jTextField_viewTaskName.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_viewTaskName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_viewTaskName.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_viewTaskName.setText("Task name");
        jTextField_viewTaskName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextField_viewTaskName.setName("jTextField_viewTaskName"); // NOI18N

        jTextField_viewTaskDate.setEditable(false);
        jTextField_viewTaskDate.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_viewTaskDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_viewTaskDate.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_viewTaskDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_viewTaskDate.setText("Due date");
        jTextField_viewTaskDate.setName("jTextField_viewTaskDate"); // NOI18N

        jScrollPane_viewTask.setName("jScrollPane_viewTask"); // NOI18N

        jTextArea_viewTaskDetails.setEditable(false);
        jTextArea_viewTaskDetails.setBackground(new java.awt.Color(224, 224, 244));
        jTextArea_viewTaskDetails.setColumns(20);
        jTextArea_viewTaskDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_viewTaskDetails.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_viewTaskDetails.setLineWrap(true);
        jTextArea_viewTaskDetails.setRows(5);
        jTextArea_viewTaskDetails.setText("Task details");
        jTextArea_viewTaskDetails.setWrapStyleWord(true);
        jTextArea_viewTaskDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextArea_viewTaskDetails.setName("jTextArea_viewTaskDetails"); // NOI18N
        jScrollPane_viewTask.setViewportView(jTextArea_viewTaskDetails);

        jLabel_viewTaskDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comment.png"))); // NOI18N
        jLabel_viewTaskDetailsIcon.setName("jLabel_viewTaskDetailsIcon"); // NOI18N

        jLabel_viewTaskDateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar.png"))); // NOI18N
        jLabel_viewTaskDateIcon.setName("jLabel_viewTaskDateIcon"); // NOI18N

        jButton_editTask.setBackground(new java.awt.Color(255, 255, 255));
        jButton_editTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editing.png"))); // NOI18N
        jButton_editTask.setBorder(null);
        jButton_editTask.setBorderPainted(false);
        jButton_editTask.setFocusPainted(false);
        jButton_editTask.setName("jButton_editTask"); // NOI18N
        jButton_editTask.setPreferredSize(new java.awt.Dimension(34, 34));
        jButton_editTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_viewTaskPanelLayout = new javax.swing.GroupLayout(jPanel_viewTaskPanel);
        jPanel_viewTaskPanel.setLayout(jPanel_viewTaskPanelLayout);
        jPanel_viewTaskPanelLayout.setHorizontalGroup(
            jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewTaskPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_viewTaskDateIcon)
                    .addComponent(jButton_viewTaskMarkCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_viewTaskPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel_viewTaskDetailsIcon)
                .addGap(18, 18, 18)
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_viewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_viewTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_viewTaskPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jTextField_viewTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_editTask, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel_viewTaskPanelLayout.setVerticalGroup(
            jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_viewTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_editTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_viewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_viewTaskDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_viewTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_viewTaskDateIcon))
                .addGap(49, 49, 49)
                .addComponent(jButton_viewTaskMarkCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_viewTaskLayout = new javax.swing.GroupLayout(jDialog_viewTask.getContentPane());
        jDialog_viewTask.getContentPane().setLayout(jDialog_viewTaskLayout);
        jDialog_viewTaskLayout.setHorizontalGroup(
            jDialog_viewTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_viewTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_viewTaskLayout.setVerticalGroup(
            jDialog_viewTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_viewTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialog_editTask.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_editTask.setTitle("Edit Task");
        jDialog_editTask.setAlwaysOnTop(true);
        jDialog_editTask.setBackground(new java.awt.Color(79, 79, 79));
        jDialog_editTask.setFocusTraversalPolicyProvider(true);
        jDialog_editTask.setIconImage(null);
        jDialog_editTask.setIconImages(null);
        jDialog_editTask.setLocation(new java.awt.Point(0, 0));
        jDialog_editTask.setMinimumSize(new java.awt.Dimension(480, 435));
        jDialog_editTask.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialog_editTask.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        jDialog_editTask.setName(""); // NOI18N
        jDialog_editTask.setResizable(false);

        jPanel_editTaskPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_editTaskPanel.setName("jPanel_editTaskPanel"); // NOI18N

        jButton_editTaskSave.setBackground(new java.awt.Color(75, 114, 153));
        jButton_editTaskSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_editTaskSave.setForeground(new java.awt.Color(255, 255, 255));
        jButton_editTaskSave.setText("Save");
        jButton_editTaskSave.setName("jButton_editTaskSave"); // NOI18N
        jButton_editTaskSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editTaskSaveActionPerformed(evt);
            }
        });

        jTextField_editTaskName.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_editTaskName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_editTaskName.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_editTaskName.setText("Enter task name");
        jTextField_editTaskName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextField_editTaskName.setName("jTextField_editTaskName"); // NOI18N
        jTextField_editTaskName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_editTaskNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_editTaskNameFocusLost(evt);
            }
        });

        jTextField_editTaskDate.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_editTaskDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_editTaskDate.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_editTaskDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_editTaskDate.setText("dd-mm-yyyy");
        jTextField_editTaskDate.setName("jTextField_editTaskDate"); // NOI18N
        jTextField_editTaskDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_editTaskDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_editTaskDateFocusLost(evt);
            }
        });

        jScrollPane_editTask.setName("jScrollPane_editTask"); // NOI18N

        jTextArea_editTaskDetails.setBackground(new java.awt.Color(224, 224, 244));
        jTextArea_editTaskDetails.setColumns(20);
        jTextArea_editTaskDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_editTaskDetails.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_editTaskDetails.setLineWrap(true);
        jTextArea_editTaskDetails.setRows(5);
        jTextArea_editTaskDetails.setText("Add task details");
        jTextArea_editTaskDetails.setWrapStyleWord(true);
        jTextArea_editTaskDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextArea_editTaskDetails.setName("jTextArea_editTaskDetails"); // NOI18N
        jTextArea_editTaskDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea_editTaskDetailsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea_editTaskDetailsFocusLost(evt);
            }
        });
        jScrollPane_editTask.setViewportView(jTextArea_editTaskDetails);

        jButton_editTaskCancel.setBackground(new java.awt.Color(75, 114, 153));
        jButton_editTaskCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_editTaskCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_editTaskCancel.setText("Cancel");
        jButton_editTaskCancel.setName("jButton_editTaskCancel"); // NOI18N
        jButton_editTaskCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editTaskCancelActionPerformed(evt);
            }
        });

        jLabel_editTaskDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comment.png"))); // NOI18N
        jLabel_editTaskDetailsIcon.setName("jLabel_editTaskDetailsIcon"); // NOI18N

        jLabel_editTaskDateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar.png"))); // NOI18N
        jLabel_editTaskDateIcon.setName("jLabel_editTaskDateIcon"); // NOI18N

        jPanel_editTaskErrorMessage.setBackground(new java.awt.Color(224, 224, 244));
        jPanel_editTaskErrorMessage.setName("jPanel_editTaskErrorMessage"); // NOI18N

        jLabel_editTaskErrorMessage.setBackground(new java.awt.Color(69, 69, 69));
        jLabel_editTaskErrorMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_editTaskErrorMessage.setForeground(new java.awt.Color(204, 0, 102));
        jLabel_editTaskErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_editTaskErrorMessage.setName("jLabel_editTaskErrorMessage"); // NOI18N

        javax.swing.GroupLayout jPanel_editTaskErrorMessageLayout = new javax.swing.GroupLayout(jPanel_editTaskErrorMessage);
        jPanel_editTaskErrorMessage.setLayout(jPanel_editTaskErrorMessageLayout);
        jPanel_editTaskErrorMessageLayout.setHorizontalGroup(
            jPanel_editTaskErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_editTaskErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_editTaskErrorMessageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_editTaskErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_editTaskErrorMessageLayout.setVerticalGroup(
            jPanel_editTaskErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
            .addGroup(jPanel_editTaskErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_editTaskErrorMessageLayout.createSequentialGroup()
                    .addComponent(jLabel_editTaskErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel_editTaskPanelLayout = new javax.swing.GroupLayout(jPanel_editTaskPanel);
        jPanel_editTaskPanel.setLayout(jPanel_editTaskPanelLayout);
        jPanel_editTaskPanelLayout.setHorizontalGroup(
            jPanel_editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_editTaskPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_editTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_editTaskPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_editTaskDetailsIcon)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_editTask, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_editTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_editTaskPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel_editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_editTaskDateIcon)
                            .addGroup(jPanel_editTaskPanelLayout.createSequentialGroup()
                                .addComponent(jButton_editTaskSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_editTaskCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel_editTaskErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_editTaskPanelLayout.setVerticalGroup(
            jPanel_editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_editTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_editTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_editTask, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_editTaskDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_editTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_editTaskDateIcon))
                .addGap(29, 29, 29)
                .addGroup(jPanel_editTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_editTaskSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_editTaskCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_editTaskErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_editTaskLayout = new javax.swing.GroupLayout(jDialog_editTask.getContentPane());
        jDialog_editTask.getContentPane().setLayout(jDialog_editTaskLayout);
        jDialog_editTaskLayout.setHorizontalGroup(
            jDialog_editTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_editTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_editTaskLayout.setVerticalGroup(
            jDialog_editTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_editTaskLayout.createSequentialGroup()
                .addComponent(jPanel_editTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialog_errorDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_errorDialog.setTitle("Error");
        jDialog_errorDialog.setAlwaysOnTop(true);
        jDialog_errorDialog.setBackground(new java.awt.Color(79, 79, 79));
        jDialog_errorDialog.setFocusTraversalPolicyProvider(true);
        jDialog_errorDialog.setIconImage(null);
        jDialog_errorDialog.setIconImages(null);
        jDialog_errorDialog.setLocation(new java.awt.Point(0, 0));
        jDialog_errorDialog.setMaximumSize(new java.awt.Dimension(480, 435));
        jDialog_errorDialog.setMinimumSize(new java.awt.Dimension(350, 220));
        jDialog_errorDialog.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialog_errorDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        jDialog_errorDialog.setName("jDialog_errorDialog"); // NOI18N
        jDialog_errorDialog.setPreferredSize(new java.awt.Dimension(350, 220));
        jDialog_errorDialog.setResizable(false);
        jDialog_errorDialog.setSize(new java.awt.Dimension(150, 150));

        jPanel_errorMessagePanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_errorMessagePanel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_errorMessagePanel.setName("jPanel_errorMessagePanel"); // NOI18N
        jPanel_errorMessagePanel.setPreferredSize(new java.awt.Dimension(150, 169));

        jTextArea_errorDialogMessage.setEditable(false);
        jTextArea_errorDialogMessage.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_errorDialogMessage.setColumns(20);
        jTextArea_errorDialogMessage.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_errorDialogMessage.setLineWrap(true);
        jTextArea_errorDialogMessage.setRows(5);
        jTextArea_errorDialogMessage.setText("Sorry, something's gone wrong. Please contact your system administrator if you require further assistance. ");
        jTextArea_errorDialogMessage.setWrapStyleWord(true);
        jTextArea_errorDialogMessage.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jTextArea_errorDialogMessage.setFocusable(false);
        jTextArea_errorDialogMessage.setName("jTextArea_errorDialogMessage"); // NOI18N
        jTextArea_errorDialogMessage.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel_errorMessagePanelLayout = new javax.swing.GroupLayout(jPanel_errorMessagePanel);
        jPanel_errorMessagePanel.setLayout(jPanel_errorMessagePanelLayout);
        jPanel_errorMessagePanelLayout.setHorizontalGroup(
            jPanel_errorMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_errorMessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea_errorDialogMessage)
                .addGap(18, 18, 18))
        );
        jPanel_errorMessagePanelLayout.setVerticalGroup(
            jPanel_errorMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_errorMessagePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTextArea_errorDialogMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton_errorDialogContinue.setBackground(new java.awt.Color(75, 114, 153));
        jButton_errorDialogContinue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_errorDialogContinue.setForeground(new java.awt.Color(255, 255, 255));
        jButton_errorDialogContinue.setText("Continue");
        jButton_errorDialogContinue.setName("jButton_errorDialogContinue"); // NOI18N
        jButton_errorDialogContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_errorDialogContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_errorDialogLayout = new javax.swing.GroupLayout(jDialog_errorDialog.getContentPane());
        jDialog_errorDialog.getContentPane().setLayout(jDialog_errorDialogLayout);
        jDialog_errorDialogLayout.setHorizontalGroup(
            jDialog_errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_errorMessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addGroup(jDialog_errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_errorDialogContinue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog_errorDialogLayout.setVerticalGroup(
            jDialog_errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_errorMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_errorDialogContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(2147483647, 400));
        setMinimumSize(new java.awt.Dimension(56, 400));
        setName("CalendarView"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel_calendarView.setMaximumSize(new java.awt.Dimension(32767, 4000));
        jPanel_calendarView.setName("CalendarView"); // NOI18N
        jPanel_calendarView.setPreferredSize(new java.awt.Dimension(557, 507));

        jLabel_calendarViewStatus.setText("Status");
        jLabel_calendarViewStatus.setName("jLabel_calendarViewStatus"); // NOI18N

        jScrollPane_calendarView.setName("calendarView"); // NOI18N
        jScrollPane_calendarView.setViewportView(null);

        jTable_calendarView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task Number", "Status", "Task", "Due date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_calendarView.setFillsViewportHeight(true);
        jTable_calendarView.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTable_calendarView.setMinimumSize(new java.awt.Dimension(75, 640));
        jTable_calendarView.setName("CalendarView"); // NOI18N
        jTable_calendarView.setRowHeight(40);
        jTable_calendarView.setSelectionBackground(new java.awt.Color(79, 79, 79));
        jTable_calendarView.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable_calendarView.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_calendarView.getTableHeader().setReorderingAllowed(false);
        jTable_calendarView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_calendarViewMouseClicked(evt);
            }
        });
        jScrollPane_calendarView.setViewportView(jTable_calendarView);
        if (jTable_calendarView.getColumnModel().getColumnCount() > 0) {
            jTable_calendarView.getColumnModel().getColumn(0).setMinWidth(0);
            jTable_calendarView.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable_calendarView.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable_calendarView.getColumnModel().getColumn(1).setMinWidth(60);
            jTable_calendarView.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable_calendarView.getColumnModel().getColumn(1).setMaxWidth(60);
            jTable_calendarView.getColumnModel().getColumn(3).setMinWidth(0);
            jTable_calendarView.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTable_calendarView.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        jPanel_addTaskButtons.setName("jPanel_addTaskButtons"); // NOI18N

        jButton_addTask.setBackground(new java.awt.Color(75, 114, 153));
        jButton_addTask.setForeground(new java.awt.Color(255, 255, 255));
        jButton_addTask.setText("Add Task");
        jButton_addTask.setName("jButton_addTask"); // NOI18N
        jButton_addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addTaskActionPerformed(evt);
            }
        });

        jButton_deleteSelectedTask.setBackground(new java.awt.Color(75, 114, 153));
        jButton_deleteSelectedTask.setForeground(new java.awt.Color(255, 255, 255));
        jButton_deleteSelectedTask.setText("Delete Selected");
        jButton_deleteSelectedTask.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_deleteSelectedTask.setName("jButton_deleteSelectedTask"); // NOI18N
        jButton_deleteSelectedTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteSelectedTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_addTaskButtonsLayout = new javax.swing.GroupLayout(jPanel_addTaskButtons);
        jPanel_addTaskButtons.setLayout(jPanel_addTaskButtonsLayout);
        jPanel_addTaskButtonsLayout.setHorizontalGroup(
            jPanel_addTaskButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addTaskButtonsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton_addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 45, Short.MAX_VALUE)
                .addComponent(jButton_deleteSelectedTask, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel_addTaskButtonsLayout.setVerticalGroup(
            jPanel_addTaskButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_addTaskButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_addTaskButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_addTask, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton_deleteSelectedTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton_calendarView_lastWeek.setBackground(new java.awt.Color(240, 240, 240));
        jButton_calendarView_lastWeek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow.png"))); // NOI18N
        jButton_calendarView_lastWeek.setBorder(null);
        jButton_calendarView_lastWeek.setName(""); // NOI18N
        jButton_calendarView_lastWeek.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton_calendarView_lastWeek.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow.png"))); // NOI18N
        jButton_calendarView_lastWeek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calendarView_lastWeekMouseClicked(evt);
            }
        });

        jButton_calendarView_nextWeek.setBackground(new java.awt.Color(240, 240, 240));
        jButton_calendarView_nextWeek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right-arrow.png"))); // NOI18N
        jButton_calendarView_nextWeek.setBorder(null);
        jButton_calendarView_nextWeek.setName("jButton_calendarView_nextWeek"); // NOI18N
        jButton_calendarView_nextWeek.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton_calendarView_nextWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calendarView_nextWeekActionPerformed(evt);
            }
        });

        jLabel_currentWeek.setText("Week #");
        jLabel_currentWeek.setName("jLabel_currentWeek"); // NOI18N

        jButton_resetSelectedWeek.setBackground(new java.awt.Color(240, 240, 240));
        jButton_resetSelectedWeek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circle-of-two-clockwise-arrows-rotation.png"))); // NOI18N
        jButton_resetSelectedWeek.setBorder(null);
        jButton_resetSelectedWeek.setFocusPainted(false);
        jButton_resetSelectedWeek.setName("jButton_resetSelectedWeek"); // NOI18N
        jButton_resetSelectedWeek.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton_resetSelectedWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetSelectedWeekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_calendarViewLayout = new javax.swing.GroupLayout(jPanel_calendarView);
        jPanel_calendarView.setLayout(jPanel_calendarViewLayout);
        jPanel_calendarViewLayout.setHorizontalGroup(
            jPanel_calendarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_calendarViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_calendarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_addTaskButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_calendarViewLayout.createSequentialGroup()
                        .addComponent(jLabel_calendarViewStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_resetSelectedWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_calendarView_lastWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_currentWeek)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_calendarView_nextWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addComponent(jScrollPane_calendarView)
        );
        jPanel_calendarViewLayout.setVerticalGroup(
            jPanel_calendarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_calendarViewLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel_calendarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_calendarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_calendarView_lastWeek, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(jButton_calendarView_nextWeek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_currentWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_calendarViewStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_resetSelectedWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_calendarView, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_addTaskButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel_calendarView);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles 'Add Task' button click - displays a dialog on screen for the user to add a new task
     * @param evt 
     */
    private void jButton_addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addTaskActionPerformed
        // Resets dialog fields
        jTextField_addTaskName.setText("Enter task name");
        jTextArea_addTaskDetails.setText("Add task details");
        jTextField_addTaskDate.setText("dd-mm-yyyy");
        jLabel_addTaskErrorMessage.setText("");
        // Sets border styles 
        jTextField_addTaskName.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextArea_addTaskDetails.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextField_addTaskDate.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        // Displays the dialog box in the centre of the parent form
        jDialog_addTask.setLocationRelativeTo(this);
        jDialog_addTask.setVisible(true);
    }//GEN-LAST:event_jButton_addTaskActionPerformed

    /**
     * Handles 'Delete Selected' button click - Removes the selected task from the view and calls for the data model to be updated
     * @param evt 
     */
    private void jButton_deleteSelectedTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteSelectedTaskActionPerformed
        int selectedRow = jTable_calendarView.getSelectedRow();
        int selectedTaskNum = (int)jTable_calendarView.getValueAt(selectedRow, 0);
        if(App.controller.deleteTask(jTable_calendarView, selectedRow, selectedTaskNum)) {
            System.out.println("Task " + selectedTaskNum + " at row " + selectedRow + " has been deleted");
        }
        jButton_deleteSelectedTask.setVisible(false);
    }//GEN-LAST:event_jButton_deleteSelectedTaskActionPerformed

    /**
     * Handles single mouse clicks - Shows the 'Delete Selected' button when a table row has been clicked (selected)
     * @param evt 
     */
    private void jTable_calendarViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_calendarViewMouseClicked
        // Resets visibility of delete button between row selections
        jButton_deleteSelectedTask.setVisible(false);
        // If the selected task number is -1 then it is a CalendarView weekday heading so the delete button is not displayed 
        int selectedTaskNum = (int)jTable_calendarView.getValueAt(jTable_calendarView.getSelectedRow(), 0);         
        if(jTable_calendarView.getSelectedRow() != -1 && selectedTaskNum != -1) {
            jButton_deleteSelectedTask.setVisible(true);
        }
    }//GEN-LAST:event_jTable_calendarViewMouseClicked

    /**
     * Handles 'Save' button click for new tasks - Calls for the new task to be added to the data model and closes the add task dialog box
     * @param evt 
     */
    private void jButton_addTaskSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addTaskSaveActionPerformed
        if(App.controller.addTask(jTable_calendarView, jTextField_addTaskName, jTextArea_addTaskDetails, jTextField_addTaskDate)) {
            jDialog_addTask.setVisible(false);
        }
        else {
            // Displays failure message to the user
            jLabel_addTaskErrorMessage.setText("Unable to add task. Contact your system administrator for assistance.");
        }
    }//GEN-LAST:event_jButton_addTaskSaveActionPerformed

    /**
     * Fires when user clicks on the 'Task Name' text field in 'Add Task' dialog - Resets field text
     * @param evt 
     */
    private void jTextField_addTaskNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addTaskNameFocusGained
        if(jTextField_addTaskName.getText().equals("Enter task name") || jTextField_addTaskName.getText().equals("*Task name is required")) {
            jTextField_addTaskName.setText("");
            jTextField_addTaskName.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
            jLabel_addTaskErrorMessage.setText("");
        }
    }//GEN-LAST:event_jTextField_addTaskNameFocusGained
    
    /**
     * Fires when user clicks away from the 'Task Name' text field in 'Add Task' dialog 
     * - Provides hint text to assist the user when filling out the field
     * @param evt 
     */
    private void jTextField_addTaskNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addTaskNameFocusLost
        if(jTextField_addTaskName.getText().equals("")) {
            jTextField_addTaskName.setText("Enter task name");
        }
    }//GEN-LAST:event_jTextField_addTaskNameFocusLost

    /**
     * Fires when user clicks on the 'Date' text field in 'Add Task' dialog - Resets field text
     * @param evt 
     */
    private void jTextField_addTaskDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addTaskDateFocusGained
        if(jTextField_addTaskDate.getText().equals("dd-mm-yyyy") ||
            jTextField_addTaskDate.getText().equals("*Date required") ||
            jTextField_addTaskDate.getText().equals("*Must be: dd-mm-yyyy")) {
            jTextField_addTaskDate.setText("");
            jTextField_addTaskDate.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
            jLabel_addTaskErrorMessage.setText("");
        }
    }//GEN-LAST:event_jTextField_addTaskDateFocusGained

    /**
     * Fires when user clicks away from the 'Date' text field in 'Add Task' dialog 
     * - Provides hint text to assist the user when filling out the field
     * @param evt 
     */
    private void jTextField_addTaskDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addTaskDateFocusLost
        if(jTextField_addTaskDate.getText().equals("")) {
            jTextField_addTaskDate.setText("dd-mm-yyyy");
        }
    }//GEN-LAST:event_jTextField_addTaskDateFocusLost

    /**
     * Fires when user clicks on the 'Description' text field in 'Add Task' dialog - Resets field text
     * @param evt 
     */
    private void jTextArea_addTaskDetailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_addTaskDetailsFocusGained
        if(jTextArea_addTaskDetails.getText().equals("Add task details")) {
            jTextArea_addTaskDetails.setText("");
            jLabel_addTaskErrorMessage.setText("");
        }
    }//GEN-LAST:event_jTextArea_addTaskDetailsFocusGained

    /**
    * Fires when user clicks away from the 'Description' text field in 'Add Task' dialog 
    * - Provides hint text to assist the user when filling out the field
    * @param evt 
    */
    private void jTextArea_addTaskDetailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_addTaskDetailsFocusLost
        if(jTextArea_addTaskDetails.getText().equals("")) {
            jTextArea_addTaskDetails.setText("Add task details");
        }
    }//GEN-LAST:event_jTextArea_addTaskDetailsFocusLost

    /**
     * Fires when the user clicks on the 'Cancel' button in 'Add Task' dialog - Closes the dialog
     * @param evt 
     */
    private void jButton_addTaskCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addTaskCancelActionPerformed
        jDialog_addTask.setVisible(false);
    }//GEN-LAST:event_jButton_addTaskCancelActionPerformed

    /**
     * Fires when the user clicks 'Mark as Completed' button in 'View Task' dialog 
     * - Closes the dialog, checks the selected task checkbox and adds a strikethrough to it
     * @param evt 
     */
    private void jButton_viewTaskMarkCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewTaskMarkCompletedActionPerformed
        jDialog_viewTask.setVisible(false);
        // Updates table model
        String[] task = App.controller.getSelectedTask();
        boolean status = Boolean.parseBoolean(task[4]);
        jTable_calendarView.getModel().setValueAt(!status, jTable_calendarView.getSelectedRow(), 1);
    }//GEN-LAST:event_jButton_viewTaskMarkCompletedActionPerformed

    /**
     * Fires when the user clicks the edit icon on view task dialog - closes view task dialog and opens the edit task dialog
     * @param evt 
     */
    private void jButton_editTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editTaskActionPerformed
        // Hides the viewTask dialog
        jDialog_viewTask.setVisible(false);
        // Populates the editTask dialog fields based on the taskNumber selected for editing
        String[] taskComponents = App.controller.getSelectedTask();
        // Removes any HTML tags from taskName
        String RegExMatchHTMLTags = "<[^>]*>";
        String taskName = taskComponents[1].replaceAll(RegExMatchHTMLTags, "");
        jTextField_editTaskName.setText(taskName);
        jTextArea_editTaskDetails.setText(taskComponents[2]);
        jTextField_editTaskDate.setText(taskComponents[3]);
        // Sets dialog position in centre of screen
        jDialog_editTask.setLocationRelativeTo(this.jScrollPane_calendarView);
        // Displays the editTask dialog
        jDialog_editTask.setVisible(true);
    }//GEN-LAST:event_jButton_editTaskActionPerformed

    /**
     * Fires when 'Save' button is clicked from the edit task dialog - Closes the dialog and calls for the data model to be updated
     * @param evt 
     */
    private void jButton_editTaskSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editTaskSaveActionPerformed
        // Checks to make sure the edited task was saved properly
        if(App.controller.editTask(jTable_calendarView, jTextField_editTaskName, jTextArea_editTaskDetails, jTextField_editTaskDate)) {
            // Re-populates data in the jTable to reflect changes
            App.controller.populateTableData(jTable_calendarView);
            jDialog_editTask.setVisible(false);
        }
        else {
            // Task did not save correctly - There will be an error message printed to console with further details
            jLabel_editTaskErrorMessage.setText("Unable to edit task. Contact your system administrator for assistance.");
        }
    }//GEN-LAST:event_jButton_editTaskSaveActionPerformed

    /**
     * Fires when user clicks on the 'Task Name' text field in 'Edit Task' dialog - Resets field text
     * @param evt 
     */
    private void jTextField_editTaskNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_editTaskNameFocusGained
        if(jTextField_editTaskName.getText().equals("Enter task name") || jTextField_editTaskName.getText().equals("*Task name is required")) {
            jTextField_editTaskName.setText("");
            jTextField_editTaskName.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
            jLabel_editTaskErrorMessage.setText("");
        }
    }//GEN-LAST:event_jTextField_editTaskNameFocusGained

    /**
    * Fires when user clicks away from the 'Task Name' text field in 'Edit Task' dialog 
    * - Provides hint text to assist the user when filling out the field
    * @param evt 
    */
    private void jTextField_editTaskNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_editTaskNameFocusLost
        if(jTextField_editTaskName.getText().equals("")) {
            jTextField_editTaskName.setText("Enter task name");
        }
    }//GEN-LAST:event_jTextField_editTaskNameFocusLost

    /**
     * Fires when user clicks on the 'Date' text field in 'Edit Task' dialog - Resets field text
     * @param evt 
     */
    private void jTextField_editTaskDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_editTaskDateFocusGained
        if(jTextField_editTaskDate.getText().equals("dd-mm-yyyy") ||
            jTextField_editTaskDate.getText().equals("*Date required") ||
            jTextField_editTaskDate.getText().equals("*Must be: dd-mm-yyyy")) {
            jTextField_editTaskDate.setText("");
            jTextField_editTaskDate.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
            jLabel_editTaskErrorMessage.setText("");
        }
    }//GEN-LAST:event_jTextField_editTaskDateFocusGained

    /**
    * Fires when user clicks away from the 'Date' text field in 'Edit Task' dialog 
    * - Provides hint text to assist the user when filling out the field
    * @param evt 
    */
    private void jTextField_editTaskDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_editTaskDateFocusLost
        if(jTextField_editTaskDate.getText().equals("")) {
            jTextField_editTaskDate.setText("dd-mm-yyyy");
        }
    }//GEN-LAST:event_jTextField_editTaskDateFocusLost

    /**
     * Fires when user clicks on the 'Description' text field in 'Edit Task' dialog - Resets field text
     * @param evt 
     */
    private void jTextArea_editTaskDetailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_editTaskDetailsFocusGained
        if(jTextArea_editTaskDetails.getText().equals("Add task details")) {
            jTextArea_editTaskDetails.setText("");
            jLabel_editTaskErrorMessage.setText("");
        }
    }//GEN-LAST:event_jTextArea_editTaskDetailsFocusGained

    /**
    * Fires when user clicks away from the 'DEscription' text field in 'Edit Task' dialog 
    * - Provides hint text to assist the user when filling out the field
    * @param evt 
    */
    private void jTextArea_editTaskDetailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_editTaskDetailsFocusLost
        if(jTextArea_editTaskDetails.getText().equals("")) {
            jTextArea_editTaskDetails.setText("Add task details");
        }
    }//GEN-LAST:event_jTextArea_editTaskDetailsFocusLost

    /**
     * Fires when user clicks on the 'Cancel' button in 'Edit Task' dialog - Closes the dialog
     * @param evt 
     */
    private void jButton_editTaskCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editTaskCancelActionPerformed
        jDialog_editTask.setVisible(false);
    }//GEN-LAST:event_jButton_editTaskCancelActionPerformed

    /**
     * Fires when user clicks on the previous week icon - Gets dates for the previous week, retrieves tasks due that week then updates the view accordingly
     * @param evt 
     */
    private void jButton_calendarView_lastWeekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calendarView_lastWeekMouseClicked
        // Moves the selected week back by one week
        App.controller.setSelectedWeek(-1);
        jLabel_currentWeek.setText(App.controller.getSelectedWeek());
        // Re-populates the table data to show the selected week
        App.controller.populateTableData(jTable_calendarView);
        DefaultTableModel tableModel = (DefaultTableModel)jTable_calendarView.getModel();
        tableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButton_calendarView_lastWeekMouseClicked

    /**
     * Fires when user clicks on the next week icon - Gets dates for the next week, retrieves tasks due that week then updates the view accordingly
     * @param evt 
     */
    private void jButton_calendarView_nextWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calendarView_nextWeekActionPerformed
        // Moves the selected week forward by one week
        App.controller.setSelectedWeek(1);
        jLabel_currentWeek.setText(App.controller.getSelectedWeek());
        // Re-populates the table data to show the selected week
        App.controller.populateTableData(jTable_calendarView);
        DefaultTableModel tableModel = (DefaultTableModel)jTable_calendarView.getModel();
        tableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButton_calendarView_nextWeekActionPerformed

    /**
     * Fires when user clicks on the reset selected week icon - Gets dates for the current week, retrieves tasks due this week then updates the view accordingly
     * @param evt 
     */
    private void jButton_resetSelectedWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetSelectedWeekActionPerformed
        // Moves the selected week to the current week
        App.controller.setSelectedWeek(0);
        jLabel_currentWeek.setText(App.controller.getSelectedWeek());
        // Re-populates the table data to show the selected week
        App.controller.populateTableData(jTable_calendarView);
        DefaultTableModel tableModel = (DefaultTableModel)jTable_calendarView.getModel();
        tableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButton_resetSelectedWeekActionPerformed

    private void jButton_errorDialogContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_errorDialogContinueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_errorDialogContinueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addTask;
    private javax.swing.JButton jButton_addTaskCancel;
    private javax.swing.JButton jButton_addTaskSave;
    private javax.swing.JButton jButton_calendarView_lastWeek;
    private javax.swing.JButton jButton_calendarView_nextWeek;
    private javax.swing.JButton jButton_deleteSelectedTask;
    private javax.swing.JButton jButton_editTask;
    private javax.swing.JButton jButton_editTaskCancel;
    private javax.swing.JButton jButton_editTaskSave;
    private javax.swing.JButton jButton_errorDialogContinue;
    private javax.swing.JButton jButton_resetSelectedWeek;
    private javax.swing.JButton jButton_viewTaskMarkCompleted;
    private javax.swing.JDialog jDialog_addTask;
    private javax.swing.JDialog jDialog_editTask;
    private javax.swing.JDialog jDialog_errorDialog;
    private javax.swing.JDialog jDialog_viewTask;
    private javax.swing.JLabel jLabel_addTaskDateIcon;
    private javax.swing.JLabel jLabel_addTaskDetailsIcon;
    private javax.swing.JLabel jLabel_addTaskErrorMessage;
    private javax.swing.JLabel jLabel_calendarViewStatus;
    private javax.swing.JLabel jLabel_currentWeek;
    private javax.swing.JLabel jLabel_editTaskDateIcon;
    private javax.swing.JLabel jLabel_editTaskDetailsIcon;
    private javax.swing.JLabel jLabel_editTaskErrorMessage;
    private javax.swing.JLabel jLabel_viewTaskDateIcon;
    private javax.swing.JLabel jLabel_viewTaskDetailsIcon;
    private javax.swing.JPanel jPanel_addTaskButtons;
    private javax.swing.JPanel jPanel_addTaskErrorMessage;
    private javax.swing.JPanel jPanel_addTaskPanel;
    private javax.swing.JPanel jPanel_calendarView;
    private javax.swing.JPanel jPanel_editTaskErrorMessage;
    private javax.swing.JPanel jPanel_editTaskPanel;
    private javax.swing.JPanel jPanel_errorMessagePanel;
    private javax.swing.JPanel jPanel_viewTaskPanel;
    private javax.swing.JScrollPane jScrollPane_addTask;
    private javax.swing.JScrollPane jScrollPane_calendarView;
    private javax.swing.JScrollPane jScrollPane_editTask;
    private javax.swing.JScrollPane jScrollPane_viewTask;
    private javax.swing.JTable jTable_calendarView;
    private javax.swing.JTextArea jTextArea_addTaskDetails;
    private javax.swing.JTextArea jTextArea_editTaskDetails;
    private javax.swing.JTextArea jTextArea_errorDialogMessage;
    private javax.swing.JTextArea jTextArea_viewTaskDetails;
    private javax.swing.JTextField jTextField_addTaskDate;
    private javax.swing.JTextField jTextField_addTaskName;
    private javax.swing.JTextField jTextField_editTaskDate;
    private javax.swing.JTextField jTextField_editTaskName;
    private javax.swing.JTextField jTextField_viewTaskDate;
    private javax.swing.JTextField jTextField_viewTaskName;
    // End of variables declaration//GEN-END:variables
}
