/*
 * BIT707 - Assignment 3
 * Jason Norton - 5001428
 */
package BIT707_A3_5001428_ToDoList;


import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;


public class ListViewForm extends javax.swing.JInternalFrame {
    public DefaultTableModel tableModel;
    /**
     * ListViewForm constructor
     */
    public ListViewForm() {
        initComponents();
        // Removes title bar from jInternalForm
        javax.swing.plaf.InternalFrameUI internalFrameUI = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)internalFrameUI).setNorthPane(null);
        
        // Hides delete button until an item is selected
        jButton_deleteSelectedTask.setVisible(false);
               
        // Gets data for the jTable
        App.controller.populateTableData(jTable_listView);  
        
        // Handles double mouse clicks on table rows
        App.controller.addTableMouseClickListener(jTable_listView, jDialog_viewTask);    
    }
        
    public void displayTask(ArrayList<String> taskComponents) {
        jTextField_viewTaskName.setText(taskComponents.get(1));
        jTextArea_viewTaskDetails.setText(taskComponents.get(2));
        jTextField_viewTaskDate.setText(taskComponents.get(3));
        // Changes button text based on task status 
        boolean status = Boolean.parseBoolean(taskComponents.get(4));
        if(status) {
            jButton_viewTaskMarkCompleted.setText("Mark as incomplete");
        }
        else {
            jButton_viewTaskMarkCompleted.setText("Mark as completed");
        }
        // Display the dialog box in the centre of the parent form
        jDialog_viewTask.setLocationRelativeTo(this.jScrollPane_listView);
        jDialog_viewTask.setName(taskComponents.get(0));
        jDialog_viewTask.setVisible(true);
    }
        
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_addTask = new javax.swing.JDialog();
        jPanel_addTaskPanel = new javax.swing.JPanel();
        jButton_addTaskSave = new javax.swing.JButton();
        jTextField_addTaskName = new javax.swing.JTextField();
        jTextField_addTaskDate = new javax.swing.JTextField();
        jScrollPane_addTask = new javax.swing.JScrollPane();
        jTextArea_addTaskDetails = new javax.swing.JTextArea();
        jButton_addTaskCancel = new javax.swing.JButton();
        jLabel_addTaskDetailsIcon = new javax.swing.JLabel();
        jLabel_addTaskDateIcon = new javax.swing.JLabel();
        jPanel_errorMessage = new javax.swing.JPanel();
        jLabel_errorMessage = new javax.swing.JLabel();
        jDialog_viewTask = new javax.swing.JDialog();
        jPanel_viewTaskPanel = new javax.swing.JPanel();
        jButton_viewTaskMarkCompleted = new javax.swing.JButton();
        jTextField_viewTaskName = new javax.swing.JTextField();
        jTextField_viewTaskDate = new javax.swing.JTextField();
        jScrollPane_viewTask = new javax.swing.JScrollPane();
        jTextArea_viewTaskDetails = new javax.swing.JTextArea();
        jLabel_viewTaskDetailsIcon = new javax.swing.JLabel();
        jLabel_viewTaskDateIcon = new javax.swing.JLabel();
        jButton_editTask = new javax.swing.JButton();
        jScrollPane_listView = new javax.swing.JScrollPane();
        jTable_listView = new javax.swing.JTable();
        jPanel_addTask = new javax.swing.JPanel();
        jButton_addTask = new javax.swing.JButton();
        jButton_deleteSelectedTask = new javax.swing.JButton();

        jDialog_addTask.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_addTask.setTitle("Add Task");
        jDialog_addTask.setAlwaysOnTop(true);
        jDialog_addTask.setBackground(new java.awt.Color(79, 79, 79));
        jDialog_addTask.setFocusTraversalPolicyProvider(true);
        jDialog_addTask.setIconImage(null);
        jDialog_addTask.setIconImages(null);
        jDialog_addTask.setLocation(new java.awt.Point(0, 0));
        jDialog_addTask.setMinimumSize(new java.awt.Dimension(480, 435));
        jDialog_addTask.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDialog_addTask.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        jDialog_addTask.setName(""); // NOI18N
        jDialog_addTask.setPreferredSize(new java.awt.Dimension(437, 390));
        jDialog_addTask.setResizable(false);

        jPanel_addTaskPanel.setBackground(new java.awt.Color(255, 255, 255));

        jButton_addTaskSave.setBackground(new java.awt.Color(75, 114, 153));
        jButton_addTaskSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_addTaskSave.setForeground(new java.awt.Color(255, 255, 255));
        jButton_addTaskSave.setText("Save");
        jButton_addTaskSave.setNextFocusableComponent(jButton_addTaskCancel);
        jButton_addTaskSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addTaskSaveActionPerformed(evt);
            }
        });

        jTextField_addTaskName.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_addTaskName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_addTaskName.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_addTaskName.setText("Enter task name");
        jTextField_addTaskName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextField_addTaskName.setNextFocusableComponent(jTextArea_addTaskDetails);
        jTextField_addTaskName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_addTaskNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_addTaskNameFocusLost(evt);
            }
        });

        jTextField_addTaskDate.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_addTaskDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_addTaskDate.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_addTaskDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_addTaskDate.setText("dd-mm-yyyy");
        jTextField_addTaskDate.setNextFocusableComponent(jButton_addTaskSave);
        jTextField_addTaskDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_addTaskDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_addTaskDateFocusLost(evt);
            }
        });

        jTextArea_addTaskDetails.setBackground(new java.awt.Color(224, 224, 244));
        jTextArea_addTaskDetails.setColumns(20);
        jTextArea_addTaskDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_addTaskDetails.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_addTaskDetails.setRows(5);
        jTextArea_addTaskDetails.setText("Add task details");
        jTextArea_addTaskDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextArea_addTaskDetails.setNextFocusableComponent(jTextField_addTaskDate);
        jTextArea_addTaskDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea_addTaskDetailsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea_addTaskDetailsFocusLost(evt);
            }
        });
        jScrollPane_addTask.setViewportView(jTextArea_addTaskDetails);

        jButton_addTaskCancel.setBackground(new java.awt.Color(75, 114, 153));
        jButton_addTaskCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_addTaskCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_addTaskCancel.setText("Cancel");
        jButton_addTaskCancel.setNextFocusableComponent(jTextField_addTaskName);
        jButton_addTaskCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addTaskCancelActionPerformed(evt);
            }
        });

        jLabel_addTaskDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comment.png"))); // NOI18N

        jLabel_addTaskDateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar.png"))); // NOI18N

        jPanel_errorMessage.setBackground(new java.awt.Color(224, 224, 244));

        jLabel_errorMessage.setBackground(new java.awt.Color(69, 69, 69));
        jLabel_errorMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_errorMessage.setForeground(new java.awt.Color(204, 0, 102));
        jLabel_errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_errorMessageLayout = new javax.swing.GroupLayout(jPanel_errorMessage);
        jPanel_errorMessage.setLayout(jPanel_errorMessageLayout);
        jPanel_errorMessageLayout.setHorizontalGroup(
            jPanel_errorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel_errorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_errorMessageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_errorMessageLayout.setVerticalGroup(
            jPanel_errorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
            .addGroup(jPanel_errorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_errorMessageLayout.createSequentialGroup()
                    .addComponent(jLabel_errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel_addTaskPanelLayout = new javax.swing.GroupLayout(jPanel_addTaskPanel);
        jPanel_addTaskPanel.setLayout(jPanel_addTaskPanelLayout);
        jPanel_addTaskPanelLayout.setHorizontalGroup(
            jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addTaskPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_addTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_addTaskPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_addTaskDetailsIcon)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_addTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_addTaskPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_addTaskDateIcon)
                            .addGroup(jPanel_addTaskPanelLayout.createSequentialGroup()
                                .addComponent(jButton_addTaskSave, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_addTaskCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel_errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_addTaskPanelLayout.setVerticalGroup(
            jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_addTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_addTaskDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_addTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_addTaskDateIcon))
                .addGap(29, 29, 29)
                .addGroup(jPanel_addTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_addTaskSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_addTaskCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_addTaskLayout = new javax.swing.GroupLayout(jDialog_addTask.getContentPane());
        jDialog_addTask.getContentPane().setLayout(jDialog_addTaskLayout);
        jDialog_addTaskLayout.setHorizontalGroup(
            jDialog_addTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_addTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_addTaskLayout.setVerticalGroup(
            jDialog_addTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_addTaskLayout.createSequentialGroup()
                .addComponent(jPanel_addTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialog_viewTask.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_viewTask.setTitle("View Task");
        jDialog_viewTask.setAlwaysOnTop(true);
        jDialog_viewTask.setBackground(new java.awt.Color(79, 79, 79));
        jDialog_viewTask.setFocusTraversalPolicyProvider(true);
        jDialog_viewTask.setIconImage(null);
        jDialog_viewTask.setIconImages(null);
        jDialog_viewTask.setLocation(new java.awt.Point(0, 0));
        jDialog_viewTask.setMinimumSize(new java.awt.Dimension(480, 435));
        jDialog_viewTask.setModalExclusionType(null);
        jDialog_viewTask.setName(""); // NOI18N
        jDialog_viewTask.setPreferredSize(new java.awt.Dimension(437, 390));
        jDialog_viewTask.setResizable(false);

        jPanel_viewTaskPanel.setBackground(new java.awt.Color(255, 255, 255));

        jButton_viewTaskMarkCompleted.setBackground(new java.awt.Color(75, 114, 153));
        jButton_viewTaskMarkCompleted.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_viewTaskMarkCompleted.setForeground(new java.awt.Color(255, 255, 255));
        jButton_viewTaskMarkCompleted.setText("Mark as completed");
        jButton_viewTaskMarkCompleted.setNextFocusableComponent(jButton_addTaskCancel);
        jButton_viewTaskMarkCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewTaskMarkCompletedActionPerformed(evt);
            }
        });

        jTextField_viewTaskName.setEditable(false);
        jTextField_viewTaskName.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_viewTaskName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_viewTaskName.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_viewTaskName.setText("Task name");
        jTextField_viewTaskName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextField_viewTaskName.setNextFocusableComponent(jTextArea_addTaskDetails);

        jTextField_viewTaskDate.setEditable(false);
        jTextField_viewTaskDate.setBackground(new java.awt.Color(224, 224, 224));
        jTextField_viewTaskDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_viewTaskDate.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_viewTaskDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_viewTaskDate.setText("Due date");
        jTextField_viewTaskDate.setNextFocusableComponent(jButton_addTaskSave);

        jTextArea_viewTaskDetails.setEditable(false);
        jTextArea_viewTaskDetails.setBackground(new java.awt.Color(224, 224, 244));
        jTextArea_viewTaskDetails.setColumns(20);
        jTextArea_viewTaskDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_viewTaskDetails.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_viewTaskDetails.setRows(5);
        jTextArea_viewTaskDetails.setText("Task details");
        jTextArea_viewTaskDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextArea_viewTaskDetails.setNextFocusableComponent(jTextField_addTaskDate);
        jScrollPane_viewTask.setViewportView(jTextArea_viewTaskDetails);

        jLabel_viewTaskDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comment.png"))); // NOI18N

        jLabel_viewTaskDateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar.png"))); // NOI18N

        jButton_editTask.setBackground(new java.awt.Color(255, 255, 255));
        jButton_editTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editing.png"))); // NOI18N
        jButton_editTask.setBorder(null);
        jButton_editTask.setBorderPainted(false);
        jButton_editTask.setFocusPainted(false);
        jButton_editTask.setPreferredSize(new java.awt.Dimension(34, 34));
        jButton_editTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_viewTaskPanelLayout = new javax.swing.GroupLayout(jPanel_viewTaskPanel);
        jPanel_viewTaskPanel.setLayout(jPanel_viewTaskPanelLayout);
        jPanel_viewTaskPanelLayout.setHorizontalGroup(
            jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewTaskPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_viewTaskDateIcon)
                    .addGroup(jPanel_viewTaskPanelLayout.createSequentialGroup()
                        .addComponent(jButton_viewTaskMarkCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel_viewTaskPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel_viewTaskDetailsIcon)
                .addGap(18, 18, 18)
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_viewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_viewTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_viewTaskPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jTextField_viewTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_editTask, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel_viewTaskPanelLayout.setVerticalGroup(
            jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_viewTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_editTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_viewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_viewTaskDetailsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_viewTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_viewTaskDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_viewTaskDateIcon))
                .addGap(49, 49, 49)
                .addComponent(jButton_viewTaskMarkCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_viewTaskLayout = new javax.swing.GroupLayout(jDialog_viewTask.getContentPane());
        jDialog_viewTask.getContentPane().setLayout(jDialog_viewTaskLayout);
        jDialog_viewTaskLayout.setHorizontalGroup(
            jDialog_viewTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_viewTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_viewTaskLayout.setVerticalGroup(
            jDialog_viewTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_viewTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(null);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(44, 100));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(406, 1463));

        jScrollPane_listView.setBorder(null);

        jTable_listView.setAutoCreateRowSorter(true);
        jTable_listView.setBackground(new java.awt.Color(255, 255, 255));
        jTable_listView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "taskNumber", "Status", "Task", "Due Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_listView.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable_listView.setMaximumSize(new java.awt.Dimension(2147483647, 128000000));
        jTable_listView.setMinimumSize(new java.awt.Dimension(165, 180));
        jTable_listView.setName(""); // NOI18N
        jTable_listView.setRowHeight(40);
        jTable_listView.setSelectionBackground(new java.awt.Color(79, 79, 79));
        jTable_listView.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable_listView.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_listView.setShowGrid(true);
        jTable_listView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_listViewMouseClicked(evt);
            }
        });
        jScrollPane_listView.setViewportView(jTable_listView);
        if (jTable_listView.getColumnModel().getColumnCount() > 0) {
            jTable_listView.getColumnModel().getColumn(0).setMinWidth(0);
            jTable_listView.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable_listView.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable_listView.getColumnModel().getColumn(1).setMinWidth(80);
            jTable_listView.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTable_listView.getColumnModel().getColumn(1).setMaxWidth(80);
            jTable_listView.getColumnModel().getColumn(3).setMinWidth(80);
            jTable_listView.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable_listView.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane_listView, java.awt.BorderLayout.CENTER);

        jPanel_addTask.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanel_addTask.setPreferredSize(new java.awt.Dimension(406, 80));

        jButton_addTask.setBackground(new java.awt.Color(75, 114, 153));
        jButton_addTask.setForeground(new java.awt.Color(255, 255, 255));
        jButton_addTask.setText("Add Task");
        jButton_addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addTaskActionPerformed(evt);
            }
        });

        jButton_deleteSelectedTask.setBackground(new java.awt.Color(75, 114, 153));
        jButton_deleteSelectedTask.setForeground(new java.awt.Color(255, 255, 255));
        jButton_deleteSelectedTask.setText("Delete Selected");
        jButton_deleteSelectedTask.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_deleteSelectedTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteSelectedTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_addTaskLayout = new javax.swing.GroupLayout(jPanel_addTask);
        jPanel_addTask.setLayout(jPanel_addTaskLayout);
        jPanel_addTaskLayout.setHorizontalGroup(
            jPanel_addTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addTaskLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton_addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(jButton_deleteSelectedTask, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel_addTaskLayout.setVerticalGroup(
            jPanel_addTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_addTaskLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel_addTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_addTask, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_deleteSelectedTask, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel_addTask, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Displays a modal dialog box on screen for user to add a new task
     * @param evt 
     */
    private void jButton_addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addTaskActionPerformed
        // Reset dialog fields
        jTextField_addTaskName.setText("Enter task name");
        jTextArea_addTaskDetails.setText("Add task details");
        jTextField_addTaskDate.setText("dd-mm-yyyy");
        jLabel_errorMessage.setText("");
        jTextField_addTaskName.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextArea_addTaskDetails.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jTextField_addTaskDate.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
        // Display the dialog box in the centre of the parent form
        jDialog_addTask.setLocationRelativeTo(this);
        jDialog_addTask.setVisible(true);
    }//GEN-LAST:event_jButton_addTaskActionPerformed

    private void jButton_addTaskSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addTaskSaveActionPerformed
        if(App.controller.addTask(jTextField_addTaskName, jTextArea_addTaskDetails, jTextField_addTaskDate)) {
             // Re-populates data in the jTable to reflect changes
            App.controller.populateTableData(jTable_listView);
            jDialog_addTask.setVisible(false);
        }
        else {
            jLabel_errorMessage.setText("Unable to add task. Contact your system administrator for assistance.");
        }
        
    }//GEN-LAST:event_jButton_addTaskSaveActionPerformed

    private void jTextField_addTaskNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addTaskNameFocusGained
        if(jTextField_addTaskName.getText().equals("Enter task name") || jTextField_addTaskName.getText().equals("*Task name is required")) {
            jTextField_addTaskName.setText("");
            jTextField_addTaskName.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
            jLabel_errorMessage.setText("");
        }
    }//GEN-LAST:event_jTextField_addTaskNameFocusGained

    private void jTextField_addTaskNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addTaskNameFocusLost
        if(jTextField_addTaskName.getText().equals("")) {
            jTextField_addTaskName.setText("Enter task name");
        }
    }//GEN-LAST:event_jTextField_addTaskNameFocusLost

    private void jTextArea_addTaskDetailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_addTaskDetailsFocusGained
        if(jTextArea_addTaskDetails.getText().equals("Add task details")) {
        jTextArea_addTaskDetails.setText("");
        jLabel_errorMessage.setText("");
        }
    }//GEN-LAST:event_jTextArea_addTaskDetailsFocusGained

    private void jTextArea_addTaskDetailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_addTaskDetailsFocusLost
        if(jTextArea_addTaskDetails.getText().equals("")) {
        jTextArea_addTaskDetails.setText("Add task details");
        }
    }//GEN-LAST:event_jTextArea_addTaskDetailsFocusLost

    private void jTextField_addTaskDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addTaskDateFocusGained
        if(jTextField_addTaskDate.getText().equals("dd-mm-yyyy") || 
        jTextField_addTaskDate.getText().equals("*Date required") || 
        jTextField_addTaskDate.getText().equals("*Must be: dd-mm-yyyy")) {
            jTextField_addTaskDate.setText("");
            jTextField_addTaskDate.setBorder(BorderFactory.createEmptyBorder(5, 15, 5, 15));
            jLabel_errorMessage.setText("");
        }
    }//GEN-LAST:event_jTextField_addTaskDateFocusGained

    private void jTextField_addTaskDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_addTaskDateFocusLost
        if(jTextField_addTaskDate.getText().equals("")) {
            jTextField_addTaskDate.setText("dd-mm-yyyy");
            
        }
    }//GEN-LAST:event_jTextField_addTaskDateFocusLost

    private void jButton_addTaskCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addTaskCancelActionPerformed
        jDialog_addTask.setVisible(false);
    }//GEN-LAST:event_jButton_addTaskCancelActionPerformed

    private void jButton_viewTaskMarkCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewTaskMarkCompletedActionPerformed
        App.controller.editTaskStatus(jTable_listView);
        jDialog_viewTask.setVisible(false);
        this.setVisible(true);
        App.controller.populateTableData(jTable_listView);
    }//GEN-LAST:event_jButton_viewTaskMarkCompletedActionPerformed

    private void jButton_editTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editTaskActionPerformed
       // TODO - Add code for editing a task
        
    }//GEN-LAST:event_jButton_editTaskActionPerformed

    private void jButton_deleteSelectedTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteSelectedTaskActionPerformed
        int selectedRow = jTable_listView.getSelectedRow();
        int selectedTaskNum = (int)jTable_listView.getValueAt(selectedRow, 0);
        if(App.controller.deleteTask(jTable_listView, selectedRow, selectedTaskNum)) {
            System.out.println("Task " + selectedTaskNum + " at row " + selectedRow + " has been deleted");
        } 
        jButton_deleteSelectedTask.setVisible(false);
               
    }//GEN-LAST:event_jButton_deleteSelectedTaskActionPerformed

    private void jTable_listViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_listViewMouseClicked
        if(jTable_listView.getSelectedRow() != -1) {
            jButton_deleteSelectedTask.setVisible(true);
        }
    }//GEN-LAST:event_jTable_listViewMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addTask;
    private javax.swing.JButton jButton_addTaskCancel;
    private javax.swing.JButton jButton_addTaskSave;
    private javax.swing.JButton jButton_deleteSelectedTask;
    private javax.swing.JButton jButton_editTask;
    private javax.swing.JButton jButton_viewTaskMarkCompleted;
    private javax.swing.JDialog jDialog_addTask;
    private javax.swing.JDialog jDialog_viewTask;
    private javax.swing.JLabel jLabel_addTaskDateIcon;
    private javax.swing.JLabel jLabel_addTaskDetailsIcon;
    private javax.swing.JLabel jLabel_errorMessage;
    private javax.swing.JLabel jLabel_viewTaskDateIcon;
    private javax.swing.JLabel jLabel_viewTaskDetailsIcon;
    private javax.swing.JPanel jPanel_addTask;
    private javax.swing.JPanel jPanel_addTaskPanel;
    private javax.swing.JPanel jPanel_errorMessage;
    private javax.swing.JPanel jPanel_viewTaskPanel;
    private javax.swing.JScrollPane jScrollPane_addTask;
    private javax.swing.JScrollPane jScrollPane_listView;
    private javax.swing.JScrollPane jScrollPane_viewTask;
    private javax.swing.JTable jTable_listView;
    private javax.swing.JTextArea jTextArea_addTaskDetails;
    private javax.swing.JTextArea jTextArea_viewTaskDetails;
    private javax.swing.JTextField jTextField_addTaskDate;
    private javax.swing.JTextField jTextField_addTaskName;
    private javax.swing.JTextField jTextField_viewTaskDate;
    private javax.swing.JTextField jTextField_viewTaskName;
    // End of variables declaration//GEN-END:variables
}
