/*
 * BIT707 - Assignment 3
 * Jason Norton - 5001428
 */
package BIT707_A3_5001428_ToDoList;

/**
 *
 * @author OEM
 */
public class ListViewForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListViewForm
     */
    public ListViewForm() {
        initComponents();
        // Removes title bar from jInternalForm
        javax.swing.plaf.InternalFrameUI internalFrameUI = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)internalFrameUI).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneListView = new javax.swing.JScrollPane();
        jTableListView = new javax.swing.JTable();
        jPanelAddTask = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(44, 100));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(406, 1463));

        jTableListView.setAutoCreateRowSorter(true);
        jTableListView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTableListView.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableListView.setMaximumSize(new java.awt.Dimension(2147483647, 128000000));
        jTableListView.setMinimumSize(new java.awt.Dimension(165, 180));
        jTableListView.setName(""); // NOI18N
        jTableListView.setPreferredSize(new java.awt.Dimension(225, 1280));
        jTableListView.setRowHeight(40);
        jTableListView.setShowGrid(true);
        jTableListView.setShowHorizontalLines(true);
        jScrollPaneListView.setViewportView(jTableListView);

        getContentPane().add(jScrollPaneListView, java.awt.BorderLayout.CENTER);

        jPanelAddTask.setMinimumSize(new java.awt.Dimension(100, 80));
        jPanelAddTask.setPreferredSize(new java.awt.Dimension(406, 80));

        jButton1.setBackground(new java.awt.Color(75, 114, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddTaskLayout = new javax.swing.GroupLayout(jPanelAddTask);
        jPanelAddTask.setLayout(jPanelAddTaskLayout);
        jPanelAddTaskLayout.setHorizontalGroup(
            jPanelAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddTaskLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanelAddTaskLayout.setVerticalGroup(
            jPanelAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddTaskLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanelAddTask, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelAddTask;
    private javax.swing.JScrollPane jScrollPaneListView;
    private javax.swing.JTable jTableListView;
    // End of variables declaration//GEN-END:variables
}
