/*
 * BIT707 - Assignment 3
 * Jason Norton - 5001428
 */
package BIT707_A3_5001428_ToDoList;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.BorderFactory;

public class MainForm extends javax.swing.JFrame {
    /**
     * Creates new MainForm which is used as a MDI container
     */
    public MainForm() {
        initComponents();
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/to-do.png"))); 
        // Sets styling for jpanel
        jPanel_titleBar.setBorder(BorderFactory.createMatteBorder(1, 0, 0, 0, Color.BLACK));    
        // Display a listView internalForm by default
        App.controller.displayListView(jDesktopPane_formContainer);
    }
        
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_titleBar = new javax.swing.JPanel();
        jLabel_appTitle = new javax.swing.JLabel();
        jButton_listView = new javax.swing.JButton();
        jButton_calendarView = new javax.swing.JButton();
        jDesktopPane_formContainer = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jPanel_titleBar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_appTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_appTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_appTitle.setText("TO DO LIST");
        jLabel_appTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton_listView.setBackground(new java.awt.Color(255, 255, 255));
        jButton_listView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/list.png"))); // NOI18N
        jButton_listView.setBorder(null);
        jButton_listView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_listView.setIconTextGap(0);
        jButton_listView.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_listView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_listViewMouseClicked(evt);
            }
        });

        jButton_calendarView.setBackground(new java.awt.Color(255, 255, 255));
        jButton_calendarView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendar.png"))); // NOI18N
        jButton_calendarView.setToolTipText("");
        jButton_calendarView.setAlignmentX(0.5F);
        jButton_calendarView.setBorder(null);
        jButton_calendarView.setFocusPainted(false);
        jButton_calendarView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_calendarView.setIconTextGap(0);
        jButton_calendarView.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_calendarView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calendarViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_titleBarLayout = new javax.swing.GroupLayout(jPanel_titleBar);
        jPanel_titleBar.setLayout(jPanel_titleBarLayout);
        jPanel_titleBarLayout.setHorizontalGroup(
            jPanel_titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_appTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                .addComponent(jButton_listView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_calendarView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel_titleBarLayout.setVerticalGroup(
            jPanel_titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleBarLayout.createSequentialGroup()
                        .addComponent(jButton_calendarView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_titleBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_listView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_appTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jDesktopPane_formContainer.setMinimumSize(new java.awt.Dimension(200, 500));
        jDesktopPane_formContainer.setName(""); // NOI18N
        jDesktopPane_formContainer.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane_formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane_formContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_listViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_listViewMouseClicked
        App.controller.displayListView(jDesktopPane_formContainer);
    }//GEN-LAST:event_jButton_listViewMouseClicked

    private void jButton_calendarViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calendarViewMouseClicked
        App.controller.displayCalendarView(jDesktopPane_formContainer);
    }//GEN-LAST:event_jButton_calendarViewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_calendarView;
    private javax.swing.JButton jButton_listView;
    private javax.swing.JDesktopPane jDesktopPane_formContainer;
    private javax.swing.JLabel jLabel_appTitle;
    private javax.swing.JPanel jPanel_titleBar;
    // End of variables declaration//GEN-END:variables
}
