/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIT707_A1_5001428_ToDoList;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       ToDoAppp classUnderTest = newToDoAppp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
